sonar.organization=brianegge
sonar.projectKey=brianegge_homeassistant-netgear-poe
sonar.sources=custom_components/netgear_poe
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
