set_port_name:
  target:
    entity:
      integration: netgear_poe
      domain: switch
  fields:
    name:
      required: true
      example: garage-cam
      selector:
        text:

get_vlan_membership:
  target:
    entity:
      integration: netgear_poe
      domain: switch
  fields:
    vlan:
      required: true
      example: 21
      selector:
        number:
          min: 1
          max: 4094
          mode: box

set_vlan_membership:
  target:
    entity:
      integration: netgear_poe
      domain: switch
  fields:
    vlan:
      required: true
      example: 21
      selector:
        number:
          min: 1
          max: 4094
          mode: box
    membership:
      required: true
      example: tagged
      selector:
        select:
          options:
            - none
            - untagged
            - tagged

set_port_speed:
  target:
    entity:
      integration: netgear_poe
      domain: switch
  fields:
    speed:
      required: true
      example: 100M
      selector:
        select:
          options:
            - auto
            - 10M
            - 100M
            - 1000M
    duplex:
      required: false
      default: auto
      example: full
      selector:
        select:
          options:
            - auto
            - half
            - full
    autoneg:
      required: false
      default: true
      selector:
        boolean:
    port:
      required: false
      example: 9
      selector:
        number:
          min: 1
          max: 52
          mode: box
